[2024-07-02T19:36:11.858+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-02T19:36:11.877+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Sectorwise_count_dag.Load_task manual__2024-07-02T19:36:02.856092+00:00 [queued]>
[2024-07-02T19:36:11.882+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Sectorwise_count_dag.Load_task manual__2024-07-02T19:36:02.856092+00:00 [queued]>
[2024-07-02T19:36:11.882+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-02T19:36:11.919+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): Load_task> on 2024-07-02 19:36:02.856092+00:00
[2024-07-02T19:36:11.923+0000] {standard_task_runner.py:63} INFO - Started process 17762 to run task
[2024-07-02T19:36:11.925+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Sectorwise_count_dag', 'Load_task', 'manual__2024-07-02T19:36:02.856092+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/Top_sector_dag.py', '--cfg-path', '/tmp/tmp1c0mfjsk']
[2024-07-02T19:36:11.926+0000] {standard_task_runner.py:91} INFO - Job 5: Subtask Load_task
[2024-07-02T19:36:11.976+0000] {task_command.py:426} INFO - Running <TaskInstance: Sectorwise_count_dag.Load_task manual__2024-07-02T19:36:02.856092+00:00 [running]> on host codespaces-3512fc
[2024-07-02T19:36:12.067+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Sabuja' AIRFLOW_CTX_DAG_ID='Sectorwise_count_dag' AIRFLOW_CTX_TASK_ID='Load_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T19:36:02.856092+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-02T19:36:02.856092+00:00'
[2024-07-02T19:36:12.068+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-02T19:36:12.069+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-07-02T19:36:12.069+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo -e ".separator ","\n.import --skip 1 /workspaces/Basic-ETL-aiflow/airflow/lab/challenge_agg_data.csv Sector_counts" | sqlite3 /workspaces/Basic-ETL-aiflow/airflow/lab/challenge.db']
[2024-07-02T19:36:12.077+0000] {subprocess.py:86} INFO - Output:
[2024-07-02T19:36:12.081+0000] {subprocess.py:93} INFO - Error: cannot open "/workspaces/Basic-ETL-aiflow/airflow/lab/challenge_agg_data.csv"
[2024-07-02T19:36:12.081+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-07-02T19:36:12.081+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-02T19:36:12.086+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-07-02T19:36:12.088+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Sectorwise_count_dag, task_id=Load_task, run_id=manual__2024-07-02T19:36:02.856092+00:00, execution_date=20240702T193602, start_date=20240702T193611, end_date=20240702T193612
[2024-07-02T19:36:12.121+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 5 for task Load_task (Bash command failed. The command returned a non-zero exit code 1.; 17762)
[2024-07-02T19:36:12.138+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-02T19:36:12.147+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-02T19:36:12.147+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
