[2024-07-02T19:39:58.379+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-02T19:39:58.402+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Sectorwise_count_dag.Load_task manual__2024-07-02T19:39:49.461134+00:00 [queued]>
[2024-07-02T19:39:58.408+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Sectorwise_count_dag.Load_task manual__2024-07-02T19:39:49.461134+00:00 [queued]>
[2024-07-02T19:39:58.408+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-02T19:39:58.444+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): Load_task> on 2024-07-02 19:39:49.461134+00:00
[2024-07-02T19:39:58.447+0000] {standard_task_runner.py:63} INFO - Started process 19400 to run task
[2024-07-02T19:39:58.450+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Sectorwise_count_dag', 'Load_task', 'manual__2024-07-02T19:39:49.461134+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/Top_sector_dag.py', '--cfg-path', '/tmp/tmpilbu26fn']
[2024-07-02T19:39:58.451+0000] {standard_task_runner.py:91} INFO - Job 8: Subtask Load_task
[2024-07-02T19:39:58.501+0000] {task_command.py:426} INFO - Running <TaskInstance: Sectorwise_count_dag.Load_task manual__2024-07-02T19:39:49.461134+00:00 [running]> on host codespaces-3512fc
[2024-07-02T19:39:58.597+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Sabuja' AIRFLOW_CTX_DAG_ID='Sectorwise_count_dag' AIRFLOW_CTX_TASK_ID='Load_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T19:39:49.461134+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-02T19:39:49.461134+00:00'
[2024-07-02T19:39:58.598+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-02T19:39:58.599+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-07-02T19:39:58.599+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo -e ".separator ","\n.import --skip 1 /workspaces/Basic-ETL-aiflow/airflow/lab/challenge_agg_data.csv Sector_counts" | sqlite3 /workspaces/Basic-ETL-aiflow/airflow/lab/challenge.db']
[2024-07-02T19:39:58.608+0000] {subprocess.py:86} INFO - Output:
[2024-07-02T19:39:58.611+0000] {subprocess.py:93} INFO - /workspaces/Basic-ETL-aiflow/airflow/lab/challenge_agg_data.csv:2: expected 2 columns but found 3 - extras ignored
[2024-07-02T19:39:58.612+0000] {subprocess.py:93} INFO - /workspaces/Basic-ETL-aiflow/airflow/lab/challenge_agg_data.csv:3: expected 2 columns but found 3 - extras ignored
[2024-07-02T19:39:58.612+0000] {subprocess.py:93} INFO - /workspaces/Basic-ETL-aiflow/airflow/lab/challenge_agg_data.csv:4: expected 2 columns but found 3 - extras ignored
[2024-07-02T19:39:58.612+0000] {subprocess.py:93} INFO - /workspaces/Basic-ETL-aiflow/airflow/lab/challenge_agg_data.csv:5: expected 2 columns but found 3 - extras ignored
[2024-07-02T19:39:58.612+0000] {subprocess.py:93} INFO - /workspaces/Basic-ETL-aiflow/airflow/lab/challenge_agg_data.csv:6: expected 2 columns but found 3 - extras ignored
[2024-07-02T19:39:58.613+0000] {subprocess.py:93} INFO - /workspaces/Basic-ETL-aiflow/airflow/lab/challenge_agg_data.csv:7: expected 2 columns but found 3 - extras ignored
[2024-07-02T19:39:58.613+0000] {subprocess.py:93} INFO - /workspaces/Basic-ETL-aiflow/airflow/lab/challenge_agg_data.csv:8: expected 2 columns but found 3 - extras ignored
[2024-07-02T19:39:58.613+0000] {subprocess.py:93} INFO - /workspaces/Basic-ETL-aiflow/airflow/lab/challenge_agg_data.csv:9: expected 2 columns but found 3 - extras ignored
[2024-07-02T19:39:58.613+0000] {subprocess.py:93} INFO - /workspaces/Basic-ETL-aiflow/airflow/lab/challenge_agg_data.csv:10: expected 2 columns but found 3 - extras ignored
[2024-07-02T19:39:58.613+0000] {subprocess.py:93} INFO - /workspaces/Basic-ETL-aiflow/airflow/lab/challenge_agg_data.csv:11: expected 2 columns but found 3 - extras ignored
[2024-07-02T19:39:58.613+0000] {subprocess.py:93} INFO - /workspaces/Basic-ETL-aiflow/airflow/lab/challenge_agg_data.csv:12: expected 2 columns but found 3 - extras ignored
[2024-07-02T19:39:58.640+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-07-02T19:39:58.641+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-02T19:39:58.679+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Sectorwise_count_dag, task_id=Load_task, run_id=manual__2024-07-02T19:39:49.461134+00:00, execution_date=20240702T193949, start_date=20240702T193958, end_date=20240702T193958
[2024-07-02T19:39:58.742+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-02T19:39:58.756+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-02T19:39:58.756+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
